const data = [
  {
    name: "The Lord of the Rings",
    author: "J. R. R. Tolkien",
    price: 876,
    published: 1878,
    subject: "Fantasy",
    img: "https://d3i5mgdwi2ze58.cloudfront.net/w9dyxnjih5pptdt5bye0f5fo79vy",
  },

  {
    name: "Nineteen Eighty Four",
    author: "George Orwell",
    price: 976,
    published: 1998,
    subject: "Politics",
    img: "https://d3i5mgdwi2ze58.cloudfront.net/bfi7lsm3qq746i49tcda0wuntedh",
  },
  {
    name: "Pride and Prejudice ",
    author: "Jane Austen",
    price: 1096,
    published: 1865,
    subject: "Motivational",
    img: "https://d3i5mgdwi2ze58.cloudfront.net/bd8er2tdfmh9auhh0v5gf90ebux5",
  },
  {
    name: "The Grapes of Wrath",
    author: "John Steinbeck",
    price: 906,
    published: 1878,
    subject: "Fantasy",
    img: "https://d3i5mgdwi2ze58.cloudfront.net/kyesti6aglwy6yocua5wr21n8l4c",
  },
  {
    name: "To Kill a Mockingbird",
    author: "Harper Lee",
    price: 896,
    published: 1878,
    subject: "Fantasy",
    img: "https://d3i5mgdwi2ze58.cloudfront.net/f286k461hpyojs41nwzenyd2sv0p",
  },
  {
    name: "Jane Eyre",
    author: "Charlotte Bronte",
    price: 676,
    published: 1865,
    subject: "Politics",
    img: "https://d3i5mgdwi2ze58.cloudfront.net/ydzg0xlc5e6680bthuefj17kqbin",
  },
  {
    name: "Wuthering Heights",
    author: "Emily Brontë",
    price: 769,
    published: 1865,
    subject: "Politics",
    img: "https://d3i5mgdwi2ze58.cloudfront.net/43ma2b4rlzqbh8181hj7dnpuz5at",
  },
  {
    name: "A Passage to India",
    author: "E. M. Forster",
    price: 806,
    published: 1878,
    subject: "Politics",
    img: "https://d3i5mgdwi2ze58.cloudfront.net/p2hxle4llr7gvki8w9cdtibe0nt5",
  },
  {
    name: "Lord of the Flies",
    author: "William Golding",
    price: 879,
    published: 1885,
    subject: "Motivational",
    img: "https://d3i5mgdwi2ze58.cloudfront.net/sgf9qv1s1sdpu2ezxqivtivvt86z",
  },
  {
    name: "Hamlet",
    author: "William Shakespeare",
    price: 777,
    published: 1898,
    subject: "Fantasy",
    img: "https://d3i5mgdwi2ze58.cloudfront.net/lunn7h6g4t5p27ene642364pu4l3",
  },
  {
    name: "A Bend in the River",
    author: "V. S. Naipaul",
    price: 870,
    published: 1998,
    subject: "Fantasy",
    img: "https://d3i5mgdwi2ze58.cloudfront.net/hkrtjws0c6b41mzo9ng8f91f30a6",
  },
  {
    name: "The Great Gatsby",
    author: "F. Scott Fitzgerald",
    price: 986,
    published: 1998,
    subject: "Literature",
    img: "https://d3i5mgdwi2ze58.cloudfront.net/4hkku1sl8y3fh8ggaazav5o65uqp",
  },
  {
    name: "The Catcher in the Rye",
    author: "J. D. Salinger",
    price: 796,
    published: 1998,
    subject: "Literature",
    img: "https://d3i5mgdwi2ze58.cloudfront.net/arrd4a0qpe7i6ff6jtfmtllqcl6v",
  },
  {
    name: "The Bell Jar",
    author: "Sylvia Plath",
    price: 889,
    published: 1865,
    subject: "Fantasy",
    img: "https://d3i5mgdwi2ze58.cloudfront.net/p2abcktc0b1qudk85uqrun0atbdw",
  },
  {
    name: "Brave New World",
    author: "Aldous Huxley",
    price: 987,
    published: 1865,
    subject: "Literature",
    img: "https://d3i5mgdwi2ze58.cloudfront.net/gusr1s7zz4o091z9ajp4zxynyepc",
  },
  {
    name: "The Diary of a Young Girl",
    author: "Anne Frank",
    price: 879,
    published: 1998,
    subject: "Politics",
    img: "https://d3i5mgdwi2ze58.cloudfront.net/e8253uks3o5cd36ff763sv6kj360",
  },
  {
    name: "Don QuixoteThe Bell Jar",
    author: "Miguel de Cervantes",
    price: 889,
    published: 1885,
    subject: "Fantasy",
    img: "https://d3i5mgdwi2ze58.cloudfront.net/gvx0r9lfgd8w3mm2ef7vssyi2aaz",
  },
  {
    name: "The Bible",
    author: "Christian Church",
    price: 809,
    published: 1885,
    subject: "Motivational",
    img: "https://d3i5mgdwi2ze58.cloudfront.net/e90tvfwlm6iq1vhsspsx9tzdxna7",
  },
  {
    name: "The Canterbury Tales",
    author: "Geoffrey Chaucer",
    price: 889,
    published: 1885,
    subject: "Literature",
    img: "https://d3i5mgdwi2ze58.cloudfront.net/xxzl7yw7wvhtib65j5t7z435kr45",
  },
  {
    name: "Ulysses",
    author: "James Joyce",
    price: 977,
    published: 1998,
    subject: "Fantasy",
    img: "https://d3i5mgdwi2ze58.cloudfront.net/f7nkbyqfsnrrlct3hs01jkrz2vdi",
  },
  {
    name: "The Quiet American",
    author: "Graham Greene",
    price: 877,
    published: 1865,
    subject: "Politics",
    img: "https://d3i5mgdwi2ze58.cloudfront.net/xuplee4yz51yje97tndzylfsoxt9",
  },
  {
    name: "Birdsong",
    author: "Sebastian Faulks",
    price: 889,
    published: 18765,
    subject: "Fantasy",
    img: "https://d3i5mgdwi2ze58.cloudfront.net/ypniwbe7o81sa6hxo41bvqvqt1up",
  },
  {
    name: "Money",
    author: "Martin Amis",
    price: 889,
    published: 1885,
    subject: "Fantasy",
    img: "https://d3i5mgdwi2ze58.cloudfront.net/utewxktipq97h1lzeh3awslylo4m",
  },
  {
    name: "Harry Potter and the Deathly Hallows",
    author: "J. K Rowling",
    price: 887,
    published: 1878,
    subject: "Politics",
    img: "https://d3i5mgdwi2ze58.cloudfront.net/w9dyxnjih5pptdt5bye0f5fo79vy",
  },
  {
    name: "Harry Potter and the Order of the PhoenixThe Bell Jar",
    author: "J. K Rowling",
    price: 880,
    published: 1878,
    subject: "Fantasy",
    img: "https://d3i5mgdwi2ze58.cloudfront.net/a79zgbedg5rhk1zb1bpe8ol15b4n",
  },
  {
    name: "Moby Dick",
    author: "Herman Melville",
    price: 899,
    published: 1885,
    subject: "Fantasy",
    img: "https://d3i5mgdwi2ze58.cloudfront.net/epke1jolmtb858vv9ctbtxpa8yi6",
  },
  {
    name: "The Wind in the Willows",
    author: "Kenneth GrahameSylvia Plath",
    price: 476,
    published: 1878,
    subject: "Literature",
    img: "https://d3i5mgdwi2ze58.cloudfront.net/nkquf3s0dc5o5x5omg0b0m06pto0",
  },
  {
    name: "His Dark Materials",
    author: "Philip Pullman",
    price: 866,
    published: 1885,
    subject: "Fantasy",
    img: "https://d3i5mgdwi2ze58.cloudfront.net/5k29dtvd2svk5rcqzl4xchkpkfto",
  },
  {
    name: "Anna Karenina",
    author: "Leo Tolstoy",
    price: 999,
    published: 1878,
    subject: "Fantasy",
    img: "https://d3i5mgdwi2ze58.cloudfront.net/kv7bohlfznregsg7wuttncytwvvv",
  },
  {
    name: "Alice's Adventures in Wonderland",
    author: "Lewis Carroll",
    price: 866,
    published: 1998,
    subject: "Literature",
    img: "https://d3i5mgdwi2ze58.cloudfront.net/f8uct7xgd8cz5cw1dsz54zc6swlc",
  },
  {
    name: "Rebecca",
    author: "Daphne du Maurier",
    price: 864,
    published: 1885,
    subject: "Fantasy",
    img: "https://d3i5mgdwi2ze58.cloudfront.net/ffal6ue3orhz8wm9m9srqok3dhqr",
  },
  {
    name: "The Curious Incident of the Dog in the Night-time",
    author: "Mark Haddon",
    price: 861,
    published: 165,
    subject: "Fantasy",
    img: "https://d3i5mgdwi2ze58.cloudfront.net/xn98c1d4al1el1i42v4bccpj5lsu",
  },
  {
    name: "On the Road",
    author: "Jack Kerouac",
    price: 555,
    published: 1878,
    subject: "Literature",
    img: "https://d3i5mgdwi2ze58.cloudfront.net/rda78z03z8r2y3dd05f2r0nemkdn",
  },
  {
    name: "Heart of Darkness",
    author: "Joseph Conrad",
    price: 777,
    published: 1998,
    subject: "Politics",
    img: "https://d3i5mgdwi2ze58.cloudfront.net/tyxilwq93riaj4702yj9ntkf6o8g",
  },
  {
    name: "The Way We Live Now",
    author: "Anthony Trollope",
    price: 995,
    published: 1998,
    subject: "Fantasy",
    img: "https://d3i5mgdwi2ze58.cloudfront.net/vvdn1n8ydlnoln81riej2pw4y5m5",
  },
];
export default data;
